### ISSUE TITLE
Cannot find name 'VideoFrame'

### ISSUE THREAD

**Issue by vvolodin** [OfficeDev/microsoft-teams-library-js#1621]
After updating to 2.9.0 teams-js breaks my build again with:

```
main.ts depends on '@microsoft/teams-js'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies



Error: node_modules/@microsoft/teams-js/dist/MicrosoftTeams.d.ts:6815:37 - error TS2304: Cannot find name 'VideoFrame'.

6815                         videoFrame: VideoFrame;
                                         ~~~~~~~~~~


Error: node_modules/@microsoft/teams-js/dist/MicrosoftTeams.d.ts:6823:97 - error TS2304: Cannot find name 'VideoFrame'.

6823                 type VideoFrameCallback = (receivedVideoFrame: MediaStreamFrameData) => Promise<VideoFrame>;
                                                                                                     ~~~~~~~~~~
```

**Comment by nwojod-MSFT** [comment]
@vvolodin thanks for reporting this. We are currently investigating this issue. We will update you on a fix.

**Comment by TrevorJoelHarris** [comment]
@vvolodin Could you tell me a little about how your build process is put together and what commands you ran to upgrade to 2.9.0 and then build? You also caught a similar issue a few months ago: https://statics.teams.cdn.office.net/evergreen-assets/safelinks/1/atp-safelinks.html

Seems pretty clear to me that we have a hole in our automation somewhere and I'd like to figure out what that is so we can avoid making more releases with this problem in the future.

**Comment by TrevorJoelHarris** [comment]
We've released 2.9.1 to fix, please try that out and let us know if you have any more problems.

**Comment by lubobill1990** [comment]
> We've released 2.9.1 to fix, please try that out and let us know if you have any more problems.

Hi @TrevorJoelHarris @nwojod-MSFT,

It seems we need to add a pipeline, like a test app to consume and build with the built SDK package.

**Comment by vvolodin** [comment]
2.9.1 fixed my issue. I don't have any special update procedure, I check for new versions of npm packages using `npm-check` utility and it installs updates via `npm i`.

**Comment by AE-MS** [comment]
> > We've released 2.9.1 to fix, please try that out and let us know if you have any more problems.
> 
> Hi @TrevorJoelHarris @nwojod-MSFT,
> 
> It seems we need to add a pipeline, like a test app to consume and build with the built SDK package.

Hi @lubobill1990, thanks for your suggestion! Though in the context of this problem it may not be apparent, we actually have a pipeline (many of them, in fact), which builds and runs a test app. It is **unquestionably** a goal of ours to not release teamsjs updates that break customer app/scenarios.

Just to provide some background on our current validation if you are interested: the repo actually contains multiple test apps ([the functionality validation app](https://github.com/OfficeDev/microsoft-teams-library-js/tree/main/apps/teams-test-app), [the performance validation app](https://github.com/OfficeDev/microsoft-teams-library-js/tree/main/apps/teams-perf-test-app), [a sample app](https://github.com/OfficeDev/microsoft-teams-library-js/tree/main/apps/sample-app), and even one written in [C# using Blazor](https://github.com/OfficeDev/microsoft-teams-library-js/tree/main/apps/blazor-test-app). For all our validation, we additionally consume the teamsjs library in two ways: once as an npm package and once leveraging the CDN package.

Our goal and expectation is that the combination of these different test apps, automated test suites, and teamsjs consumption methods _should_ prevent breaks like this. On every check-in (and consequently on every release), every single capability and every single function in the teamsjs library is validated in the context of a test host using one or more of these apps. To further prevent breaks, our automated pipeline even validates backwards compatibility with previous releases of teamsjs to ensure that nothing about the communication changed version over version (going all the way back to 1.12.1).

Despite this, obviously, breaks do still occur. Our commitment is that every single break like this undergoes a root cause and additional validation is added to prevent a similar break from reoccurring. That root cause process is happening right now as a result of this exact break. While we are still in the process of understanding how to detect this particular problem and validate it, it seems like the problem is coming from the fact that our test apps are built from within the same monorepo as the teamsjs library itself, enabling them to "accidentally" leverage dependencies consumed by other projects within the monorepo without have to explicitly declare them. As I said, we're still validating that is indeed the case here, but that lack of build isolation is the current most promising lead we are chasing down.

Regardless of what the actual cause turns out to be, we will be ensuring that we can protect against such breaks in the future by extending our existing automated validation process.

Does that help provide some context for how we validate releases and treat issues like this?

**Comment by vvolodin** [comment]
I've just updated to 2.10.0 and this again:
```
Error: node_modules/@microsoft/teams-js/dist/MicrosoftTeams.d.ts:6851:37 - error TS2304: Cannot find name 'VideoFrame'.

6851                         videoFrame: VideoFrame;
                                         ~~~~~~~~~~


Error: node_modules/@microsoft/teams-js/dist/MicrosoftTeams.d.ts:6859:97 - error TS2304: Cannot find name 'VideoFrame'.

6859                 type VideoFrameCallback = (receivedVideoFrame: MediaStreamFrameData) => Promise<VideoFrame>;
                                                                                                     ~~~~~~~~~~




✖ Failed to compile.
```

**Comment by TrevorJoelHarris** [comment]
@vvolodin I'm sorry you've run into this again. We're currently working on reverting and putting out a new release, and I promise that the change that has been causing this break won't make it back into the build until we have automation that is designed to catch these sort of breaks in place. One of our engineers (@jadahiya-MSFT ) will reach out to you later this month to gather more details and make sure we have a fix in place that will prevent this from happening again.

**Comment by TrevorJoelHarris** [comment]
@vvolodin We've released v 2.10.1 which should fix this issue. Please let me know if you notice any other issues.

https://github.com/OfficeDev/microsoft-teams-library-js/releases/tag/v2.10.1

Sorry again for any inconvenience!

**Comment by vvolodin** [comment]
Thanks, this has fixed the issue!

**Comment by WengHe** [comment]
Hi @vvolodin we are trying to find the root cause of this issue and create a test against this issue to prevent it from happening again. If it is convenient for you, could you let me know what your tsconfig.json looks like, especially, do you specify `typeRoots` or `types` in the tsconfig.json?

Also, I prepared a new package, trying to fix the issue, could you help to try it? You could replace the `@microsoft/teams-js` with this package:
https://github.com/WengHe/microsoft-teams-library-js/releases/download/issue-1621/microsoft-teams-js-issue-1621.tgz and see if the issue won't happen again.

Ex:
```
// package.json
{
...
  dependencies:
  {
    "@microsoft/teams-js": "https://github.com/WengHe/microsoft-teams-library-js/releases/download/issue-1621/microsoft-teams-js-issue-1621.tgz"
  }
...
}
