### ISSUE TITLE
2.4.0 does not compile

### ISSUE THREAD

**Issue by vvolodin** [OfficeDev/microsoft-teams-library-js#1382]
My app stopped compiling after updating teams-js to 2.4.0:

Error: node_modules/@microsoft/teams-js/dist/MicrosoftTeams.d.ts:6:90 - error TS2307: Cannot find module '@fluidframework/azure-client' or its corresponding type declarations.

6 import type { AzureConnectionConfig, AzureContainerServices, ITelemetryBaseLogger } from '@fluidframework/azure-client';
                                                                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: node_modules/@microsoft/teams-js/dist/MicrosoftTeams.d.ts:7:55 - error TS2307: Cannot find module '@fluidframework/fluid-static' or its corresponding type declarations.

7 import type { ContainerSchema, IFluidContainer } from '@fluidframework/fluid-static';

**Comment by Meghana-MSFT** [comment]
Did deleting node modules and package-lock.json help? Meanwhile could you please share the sample/minimal code that you are trying. So that we can check for repro at our end as well.

**Comment by Stevenic** [comment]
@vvolodin  we're working on a fix but we're trying to better understand the nature of the issue. Can you tell me, does your app pull in any separate packages that have a dependency on teams-js? This error isn't occurring for all applications and we have at least one large complex application with nested dependencies where it is occurring so trying to isolate the trigger.

**Comment by vvolodin** [comment]
No, teams-js is a direct dependency in my project, and judging it only occurs a couple of times in `package-lock.json` there are no other libraries depending on it.
I do updates frequently (angular, ngrx, etc.) and very rarely have to remove my `node_modules`.

**Comment by nwojod-MSFT** [comment]
@vvolodin like Steve pointed above, we are working on a fix. We have reverted the release while we address some issues. To unblock you, please pull the @latest version of the TJS SDK which will point to v2.3.0. We will update this thread when the fix is complete.

**Comment by jadahiya-MSFT** [comment]
@vvolodin We've rolled back version 2.4.0 to 2.3.0 (latest now points to 2.3.0), while we work to fix this in a future release. Please let me know if there are any errors with the rolled back version. Thanks.

**Comment by nwojod-MSFT** [comment]
@vvolodin we have fixed this and rolled out version 2.4.1. Please update your sdk to the latest version and let us know if you are still experiencing this issue. Thanks.

**Comment by nwojod-MSFT** [comment]
Please reopen issue if still experiencing the error.

**Comment by vvolodin** [comment]
Everything compiled successfully after updating to 2.4.1. Thank you.
